config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls'))
]

pybo/urls.py
from django.contrib import admin
from django.urls import path
from pybo import views

app_name = 'pybo'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('<int:question_id>', views.detail, name='detail')
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models


# Create your models here.


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

pybo/forms.py
from django import forms
from pybo.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용'
        }

pybo/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView
from pybo.models import Question  # , Answer
from .forms import QuestionForm


# Create your views here. -> input validate, model call, context에 data저장, UI select


# 목록 출력
# def index(request):
#     object_list = Question.objects.order_by('-create_date')
#     context = {'object_list': object_list}
#     return render(request, 'pybo/question_list.html', context)
#
#
# def detail(request, question_id):
#     # question = Question.objects.get(pk=question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'object': question}
#     return render(request, 'pybo/question_detail.html', context)


class IndexView(ListView):
    model = Question

    def get_queryset(self):
        return Question.objects.order_by('-create_date')


class DetailView(DetailView):
    model = Question


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    # answer = Answer(question=Question.objects.get(id=question_id),
    #          content=request.POST.get('content'), create_date=timezone.now())
    # answer.save()
    return redirect('pybo:detail', pk=question.id)


# question 등록 화면 : get 입력화면 post - form(subject, content) 데이터 model 저장
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)   # subject = subject.POST['subject'],
                                            # content = content.POST['content']
        if form.is_valid():
            question = form.save(commit=False)  # question = Question(subject=subject,
                                                # content=content, create_date=timezone.now())

            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="eng">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css.map' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.4.1.min.js' defer %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' defer %}" ></script>

    <title>Python Board</title>
</head>
<br>
<body>
<!-- 네비게이션바 -->
{% include 'navbar.html' %}
<!-- 기본적으로 추가 될 내용 -->
    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="#">로그인</a>
            </li>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ object.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ object.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ object.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{object.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in object.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' object.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3" action="{% url 'pybo:question_create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' object.id %}">{{ object.subject }}</a>
            </td>
            <td>{{ object.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}